---
# yamllint disable rule:line-length
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-tabs
        exclude_types: [python, javascript, dtd, markdown, makefile, xml]
        exclude: binary|\.bin$
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: 0.0.2
    hooks:
      - id: shell-lint
        exclude: template|\.template$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/jameswoolfenden/pre-commit
    rev: v0.1.50
    hooks:
      - id: terraform-fmt
        language_version: python3.9
      - id: tf2docs
        language_version: python3.9
  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.3.198
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d example/examplea --external-checks-dir checkov --download-external-modules true --compact
  - repo: https://github.com/jameswoolfenden/pike
    rev: v0.2.73
    hooks:
      - id: pike-docs-go
        args: ["readme","-d", ".", "-i"]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.19.0
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ['--config', 'auto']
  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec
        name: TFSec
        description: TFsec is a tool to statically analyze Terraform templates to spot potential security issues.
        language: golang
        entry: tfsec --include-passed
        pass_filenames: false
