---
# yamllint disable rule:line-length
version: 0.2
env:
  parameter-store:
    BUILDNUMBER: /core/codebuild/examplea/buildnumber

phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
      - export MAJOR=0
      - export MINOR=0
      - BUILDNUMBER=$(BUILDNUMBER + 1)
      - export BUILDNUMBER=$BUILDNUMBER
      - aws ssm put-parameter --name "/core/codebuild/examplea/buildnumber" --type "String" --value "$BUILDNUMBER" --overwrite
      - export BUILDVERSION=$MAJOR.$MINOR.$BUILDNUMBER
      - echo "Running - $BUILDVERSION"
  build:
    commands:
      - echo "build command"
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then aws ssm put-parameter --name "/core/codebuild/examplea/latest" --type "String" --value "$BUILDVERSION" --overwrite; else echo Build failed; fi
      - echo "post_build step"
