version: 0.2
env:
  variables:
    MAJOR: "1"
    MINOR: "1"
  parameter-store:
    BUILDNUMBER: =/core/codebuild/exampleA/buildnumber

phases:
  install:
    commands:
      - apk add python python-dev py-pip build-base
      - apk add jq
      - pip install --upgrade pip
      - pip install awscli
  pre_build:
    commands:
      - echo "pre_build step"
      - export MAJOR=0
      - export MINOR=0
      - . ./buildno.sh
      - export BUILDVERSION=$MAJOR.$MINOR.$BUILDNUMBER
      - echo "Running - $BUILDVERSION"
  build:
    commands:
      - echo "build command"
      - BUILDVERSION=$BUILDVERSION npm run version
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then aws ssm put-parameter --name "/core/codebuild/exampleA/latest" --type "String" --value "$BUILDVERSION" --overwrite; else echo Build failed; fi
      - echo "post_build step"
