version: 0.2
env:
  variables:
    environment: "dev"
    MAJOR: "1"
    MINOR: "1"
phases:
  install:
    commands:
      - apk add python python-dev py-pip build-base
      - apk add jq
      - pip install --upgrade pip
      - pip install awscli
  pre_build:
    commands:
      - echo "pre_build step"
      - export MAJOR=0
      - export MINOR=0
      - . ./buildno.sh
      - export BUILDVERSION=$MAJOR.$MINOR.$BUILDNUMBER
      - echo "Running - $BUILDVERSION"
  build:
    commands:
      - echo "build command"
      - BUILDVERSION=$BUILDVERSION npm run version
      - echo "$yo"
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then . ./setlatest.sh; else echo Build failed; fi
      - echo "post_build step"
